### ISSUE TITLE
Převod dat gmail.com -> skaut.cz

### ISSUE THREAD

**Issue by kalich5** [skaut/shared-drive-mover#136]
Mám problém, nechce se to pustit na gmail.com účtu.

Pod gmail.com účtem jsou nějaká data na disku. A chtěl bych je přenést na sdílený disk pod skaut.cz. Ale skončí to už na začátku chybou...
![image](https://user-images.githubusercontent.com/8988898/72225705-d09d1000-3588-11ea-8795-dbd7c182b470.png)

**Comment by marekdedic** [comment]
Ahoj,
máš to rozjeté ve své instanci, nebo to zkoušíš na té, kterou jsem dělal já? Ta je omezená na doménu skaut.cz.

**Comment by kalich5** [comment]
Zkouším postupovat přes ten odkaz, takže přes to co jsi dělal ty.

Je nějaký důvod? Kámoš řeší přesun z klasického Gmailu... a podle mě takových lidí může být víc

**Comment by marekdedic** [comment]
Jo, tak to je ten důvod proč to nejde.

V zásadě je několik důvodů, proč jsem to omezil na uživatele v doméně:
- pokud jsem to dobře pochopil, jsou tam nějaký kvóty, i když jsou hodně vysoký.
- nechci být zodpovědný za to, co si random lidi provedou se svými daty
- nechci k tomu dělat support
- teoreticky by se to úplně nemuselo líbit Googlu, i když je asi mizivá šance, že si toho všimne.

**Comment by kalich5** [comment]
Takže si tu složku nasdílet do svého skaut účtu a pak to převést? To je jediná cesta?

**Comment by marekdedic** [comment]
Ano, to je "intended workflow".
